services:
  - type: web
    name: vision-rag-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_VISION_MODEL
        value: meta-llama/llama-4-scout-17b-16e-instruct
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: UPLOAD_DIR
        value: data/uploads
      - key: PDF_DPI
        value: "300"
    healthCheckPath: /health
